const express = require('express');
const c = require('../controllers/operationsController');
const router = express.Router();
router.get('/accounts', c.listAccounts);
router.get('/accounts/:accountNumber/statement', c.accountStatement);
router.get('/beneficiaries', c.listBeneficiaries);
router.post('/beneficiaries', c.addBeneficiary);
router.get('/reports/transactions', c.transactionReport);
router.get('/reports/settlement', c.settlementReport);
router.get('/reports/reconciliation', c.reconciliationReport);
router.get('/monitoring/api-logs', c.apiLogs);
router.get('/monitoring/alerts', c.alerts);
router.get('/monitoring/system-health', c.systemHealth);
router.get('/settings/users', c.users);
router.post('/settings/users', c.createUser);
router.get('/settings/roles', c.roles);
router.get('/settings/system', c.systemSettings);
router.put('/settings/system', c.saveSystemSetting);
module.exports = router;
